terraform-aws-modules/terraform-aws-cloudfront

versions.tf

Bumps the aws provider version due to a rename of cloudfront distribution property.
See #3 
Anyone using this module with < 3.0 should not be able to plan anyways.
When attempting to use the module, I stumbled upon this.  See #3 for a test file you can dump into a temp directory and run terraform init and plan.  When using the file as is, the error can be observed.  When the provider version is updated to 3.0, no error is provided.

fix: Updates aws provider to at least 3.0.0

---

README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
main.tf
outputs.tf
versions.tf

Adds outputs for origin access identities.
We desired to use the origin access identities in our s3 bucket policy
No
```
$ terraform -v
Terraform v0.12.29
+ provider.aws v3.11.0
+ provider.null v2.1.2
+ provider.random v2.3.0
```
We have deployed this in two environments successfully.  Here is a snippet:
```hcl
data "aws_s3_bucket" "upload-bucket" {
bucket = "uploads.example.com"
}
module "cdn" {
source = "../terraform-aws-cloudfront"
// ....
}
data "aws_iam_policy_document" "s3_policy" {
statement {
actions   = ["s3:GetObject"]
resources = ["${data.aws_s3_bucket.upload-bucket.arn}/uploads/*"]
principals {
type        = "AWS"
identifiers = [for k, v in module.cdn.this_cloudfront_origin_access_identity_iam_arns : v]
}
}
}
resource "aws_s3_bucket_policy" "cdn-bucket-policy" {
bucket = …
```

feat: Adds outputs for origin access identities

---

.gitignore
.pre-commit-config.yaml
README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/outputs.tf
outputs.tf

Change the output types of `this_cloudfront_origin_access_identity_ids` and `this_cloudfront_origin_access_identity_iam_arns` to simple lists and add `this_cloudfront_origin_access_identities` as a map with the full origin access identities.
Currently a map of origin access identities with ids and arns are available through `this_cloudfront_origin_access_identity_ids` and  `this_cloudfront_origin_access_identity_iam_arns`. The outputs are needed but the names give the wrong idea of the type to expect.
This PR will change the output types to lists, making it easier to use in S3 bucket policies etc. If you still need the full origin access identities or want to specify a single one they will be available through the new `this_cloudfront_origin_access_identities` output.
This PR will break …

refactor: change origin access identity output types

---

README.md
examples/complete/README.md
main.tf
variables.tf

…cate inside the for_each loop
The for_each loop is not needed for viewer_certificate (1 block maximum can be used) and it generates errors when the viewer_certificate var is not used as input of the module.
When we don't put the viewer_certificate block there are multiple errors on plan and apply like the error below: 
```
on terraform-aws-cloudfront/main.tf line 187, in resource "aws_cloudfront_distribution" "this":
187:       acm_certificate_arn            = lookup(var.viewer_certificate, "acm_certificate_arn", null)
|----------------
| var.viewer_certificate is null
Invalid value for "inputMap" parameter: argument must not be null.
```
This fix should not break anything. 
This code has only been tested with a configuration that does not specify the viewer_certificate block

fix: Fixed viewer_certificate variable

---

README.md
examples/complete/main.tf
main.tf
variables.tf

Separate variables for default and ordered cache behavior. 
Ordered cache behavior is now a list so that ordering is respected.
It preserves the ordering of [cache behaviors](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#ordered_cache_behavior), so that the resulting precedence is correct.
Fixes [issue 11](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/issues/11).
Yes, because a variable has been removed (cache_behavior), and two new ones were added (default_cache_behavior and ordered_cache_behavior).
It is necessary because the root of the problem was in the variable definition itself, i.e. using a map to store an ordered list.
I adapted the _examples/complete_ and planned it.
Additionally, we used our local fork …

fix: preserve ordering of cache behaviors

---

README.md
examples/complete/README.md
examples/complete/versions.tf
main.tf
versions.tf

Recently, AWS started to offer to assigned managed policies to caching:
- Managed-CachingOptimized
- Managed-CachingDisabled
- Managed-CachingOptimizedForUncompressedObjects
- Managed-Elemental-MediaPackage
This change is considered to be like a step to easier setup of CF.
No breaking changes.
Tested on creation of the new resource / update of resource created w/o managed policy.
If CDN was created w/o managed policy, it possibly would throw an error in time of apply:
`The parameter ForwardedValues cannot be used when a cache policy is associated to the cache behavior.`

add origin_request_policy_id & cache_policy_id to caching

---

.github/workflows/pre-commit.yml
README.md
examples/complete/README.md

- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks

chore: update documentation and pin `terraform_docs` version to avoid future changes

---

main.tf

This is to add  support for trusted_key_groups to ordered cache behavior same as was done here in #33 
Adding support for  trusted_key_groups in ordered_cache_behavior looking at this as finishing #33
No braking changes.
Although in related issue #30 it is stated that it is not possible to do this in ordered cache behaviors.
Planing the examples gives no errors and currently using this code in a project. 
```
+ ordered_cache_behavior {
+ allowed_methods        = [
+ "GET",
+ "HEAD",
+ "OPTIONS",
]
+ cached_methods         = [
+ "GET",
+ "HEAD",
]
+ compress               = true
+ default_ttl            = (known after apply)
+ max_ttl                = (known after apply)
+ min_ttl                = 0
+ path_pattern           = "/static/*"
+ target_origin_id       = "s3_one"
+ …
```

feat: Adding support for trusted_key_groups in ordered_cache_behavior

---

main.tf

Provide empty string as default origin path in order to avoid unneces…
This change replaces the default value of origin_path from null to an empty string
If this value remains as null, instead of an empty string, it keeps recreating the resource at every modification, however small it maybe: adding a new origin or even so small as modifying the domain_name for a custom-origin in CDN
This is related to an Open PR on aws-provider for Terraform at https://github.com/hashicorp/terraform-provider-aws/issues/12065 and is a suggestion from wamonite on the thread that points out that a regular _terraform plan_ wouldn't show the variation in origin_path attribute. 
Does not break anything as null is simply replaced by an empty string
- [YES ] I have tested and validated these changes using one or …

fix: Use empty origin_path by default

---

main.tf

Defaulting "Cache Based on Selected Request Headers" to an empty string
The headers are never updated or picked up by Terraform consistently, because they are defaulted to null. Due to this, when you wish to remove the attribute (say, "Accept" header), it simply won't accept an empty string in a list and throw an error. Removing the attribute (or even commenting it) altogether doesn't help either: it is simply ignored by Terraform provider! 
I wanted to open an Issue, but I already found the root cause and solution, and so no issue was opened by me
It does not break anything and only sets a default value of an empty string
- [x ] I have tested and validated these changes using one or more of the provided `examples/*` projects
I tested it on my enterprise staging environment
Terraform …

fix: Use empty list for headers by default instead of null

---

README.md
examples/complete/README.md
examples/complete/example-function.js
examples/complete/main.tf
main.tf
versions.tf

Adds support for [CloudFront Functions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html) - Terraform docs at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#function-association
Supporting new functionality
None
I'm in the process of testing this in a private project, but I'm opening this PR already for some feedback

feat: Support for CloudFront Functions

---

main.tf

It will allow to add the ARN of an **_existing_** real-time log configuration.
I was not able to manage via terraform an existing/manually deployed Cloudfront with a log config : cloudfront was about to delete it
https://github.com/terraform-aws-modules/terraform-aws-cloudfront/issues/16
It was tested on my own Cloudformation  : 
Before : 
```
Terraform will perform the following actions:
~ resource "aws_cloudfront_distribution" "this" {
id                             = "E2TEBV3BV4BD7"
tags                           = {}
~ default_cache_behavior {
- realtime_log_config_arn = "arn:aws:cloudfront::1234567890:realtime-log-config/aws-logs-cloudfront" -> null
}
- ordered_cache_behavior {
```
After : 
```
Terraform will perform the following actions:
~ resource "aws_cloudfront_distribution" …
```

feat: Add support of realtime_log_config_arn (no creation)

---

README.md
examples/complete/main.tf

Add `TLSv1.1` and `TLSv1.2` in `origin_ssl_protocols` examples.
TLSv1 is deprecated. We should encourage usage of TLSv1.2 everywhere, hence adding it in examples.
No breaking changes, protocols have been added.
I did not test changes as it's in the documentation.

docs: Add TLSv1.1 and TLSv1.2 for origin_ssl_protocols in examples

---

main.tf

Performing an update that requires a new Cloudfront Origin Access (OAI) resource will fail since the current OAI resource is being used and cannot be removed. Setting `create_before_destroy = true` ensures that terraform will only try to remove after the new OAI resource has replaced the old one.
Closes https://github.com/terraform-aws-modules/terraform-aws-cloudfront/issues/61
N/A
Manually on test environment.

fix: Add lifecycle clause for aws_cloudfront_origin_access_identity

---

examples/complete/main.tf

Wrong definition of s3 grant in example.
Fix wrong definition of s3 grant in example.
cf. https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/162
No breaking changes.
example changes only, no source code changes

docs: Wrong definition of s3 grant in example

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
main.tf
versions.tf
wrappers/README.md
wrappers/main.tf
wrappers/outputs.tf
wrappers/variables.tf
wrappers/versions.tf

Support for new origin parameter "origin_access_control_id" introduced in 4.29.0 of aws provider.
provider version >= 4.29.0

feat!: Added support for origin_access_control_id, bumped AWS provider version

---

README.md
variables.tf

Fix a small typo in the description for the `wait_for_deployment` variable.
This is a no-op change, just improving the text of the description.
Not a breaking change, not really a change at all.
Not tested, it's just fixing a typo.

docs: Fix typo in variable description

---

examples/complete/main.tf
main.tf

Fixes #88 
Valid inputs:
```
custom_error_response = {
error_code         = 404
response_page_path = "/errors/404.html"
}
```
or 
```
custom_error_response = [{
error_code         = 404
response_page_path = "/errors/404.html"
}, {
error_code         = 403
response_page_path = "/errors/403.html"
}
]
```

fix: Updated handling of one or many custom_error_response values

---

examples/complete/main.tf

We recently add the OAC support with https://github.com/terraform-aws-modules/terraform-aws-cloudfront/pull/97 but we didn't give a complete example on how to use it : we need to add an IAM policy on the bucket
I completed the example with the IAM code required.

chore: Updated S3 bucket policy for OAC in the complete example

---

README.md
examples/complete/main.tf
variables.tf

Update readme about possible http_version input after terraform support http3 option for cloudfront.
When people read current documentation, they won't know that actually the module already support http3 option 
no

fix: Fixed possible values for http_version input

---

README.md
examples/complete/main.tf
main.tf
variables.tf
wrappers/main.tf

* Support for staging distribution feature.
* add `staging` variable
* add `continuous_deployment_policy_id` variable
Closes #131 
In order to use staging distribution feature, we must set `staging = true` to the staging distribution and specify `continuous_deployment_policy_id` for the primary distribution.
So I added these variables.
No breaking changes.
```
❯ pre-commit run -a 
Terraform fmt............................................................Passed
Terraform wrapper with for_each in module................................Passed
Terraform validate.......................................................Passed
Terraform docs...........................................................Passed
Terraform validate with tflint...........................................Passed
check for merge …
```

feat: Added support for Staging Distribution

---

README.md
versions.tf

AWS Terraform provider version lower than [5.12.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5120-august-10-2023) doesn't support `staging` and `continuous_deployment_policy_id` params which were added in the new version [v3.3.0](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/releases/tag/v3.3.0) of this module.
Set and new min version of Terraform provider
It fixes failing plan/applies when AWS Terraform provider version lower than 5.12.0
Yes, this looks like breaking change and requires a new major version of module. However, it's already broken...

fix: Fix provider version for `staging` and `continuous_deployment_policy_id` params

---

.github/workflows/lock.yml
.github/workflows/pr-title.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/stale-actions.yaml
.pre-commit-config.yaml
examples/complete/README.md
examples/complete/example-function.js
examples/complete/versions.tf

- Update CI workflow versions to remove deprecated runtime warnings
- Updates our workflows to use the latest versions
- Removes the `deprecated runtime` warnings from the workflow execution output
- No

fix: Update CI workflow versions to remove deprecated runtime warnings
